### ISSUE TITLE
Can't make file with the release_mt tag

### ISSUE THREAD

**Issue by ChienKaiMa** [jordanpui/ripplefpga#2]
(I have modified ```src/Makefile``` to match the versions of gcc and boost.)
I have faced issues when it is fetching the ```gd.h``` file, which I believe is some packages used for debug mode.  I could have solved the issue by deleting all the codes related to ```draw.h```, but that would waste me plenty of time.

Below is the error message:
```
g++ -std=c++11  -I. -I../../boost_1_71_0 -O3 -DNDEBUG -static -Wall -MMD -MP -o main.o -c main.cpp
In file included from ./utils/misc.h:3,
                 from ./global.h:32,
                 from db/db.h:3,
                 from main.cpp:1:
./utils/draw.h:3:10: fatal error: gd.h: No such file or directory
    3 | #include <gd.h>
      |          ^~~~~~
compilation terminated.
```

**Comment by ChienKaiMa** [comment]
I was not familiar with Makefile rules, and I figured out that I have to download boost and libgd by tar.gz, unzipping them in the following structure to successfully make file.
```
├──boost_1_73_0
│   └── all the files in libgd-gd-2.3.0
└──ripple-fpga
    ├──src
    └──rest of the files
```

**Comment by jordanpui** [comment]
if you are using ubuntu, I think install boost with apt will just be fine. Anyway, it's fine that you worked it out.
