### ISSUE TITLE
Generation of RippleFPGA Input FIles from Vivado

### ISSUE THREAD

**Issue by zslwyuan** [jordanpui/ripplefpga#3]
Hi!

RippleFPGA is so comprehensive that I wonder whether we can export some designs from Vivado and test them with it. I notice that Vivado can export DCP file but RippleFPGA also requires files with suffixes like, .aux, .scl, .pl and so on, which I failed to find in the documentation of Vivado.

Thanks in advance for your help! ^_^

Best regards,
TIngyuan

**Comment by jordanpui** [comment]
rippleFPGA read designs in bookshelf format. Haven't tried what you said but I doubt that it will work.
