### ISSUE TITLE
make debug build

### ISSUE THREAD

**Issue by tbabm93** [jordanpui/ripplefpga#4]
Dear sir,

I compiled your source code with the command "make mode=debug", but it failed and the log shows "xxxx can not be used when making a PIE object,recompile with -fPIC".

I searched on internet, and i found by adding compile option "-no_pie" to Makefile, the issue can be fixed. 
Does it ever happened to you?

Thanks,
Liran

**Comment by jordanpui** [comment]
I don't remember this issue. Because we used old version of gcc and etc., this may happen.
